# GitHub Actions Workflow: Build and Deploy Conda Package
#
# Description
# -----------
# This workflow builds Conda packages from the `conda.recipe/` directory
# and deploys them to the `eresthina-conda-channel` repository. 
# It supports builds for Linux, macOS, and Windows platforms.
#
# Requirements
# ------------
# - The package repository must define a valid Conda recipe in `conda.recipe/`.
#
# - Two secrets must be defined in the repository:
#
#   - `GH_TOKEN`: GitHub Personal Access Token with write access to the channel repository.
#   - `GH_USERNAME`: GitHub username associated with the token, i.e. "esther-poniatowski".
#
# Output
# ------
# Updated Conda package artifacts and metadata in the appropriate platform subdirectory
# of `eresthina-conda-channel/`.
#
# Trigger
# -------
# On every push to any branch.

name: Build and Deploy

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            platform: linux-64
          - os: macos-latest
            platform: osx-64
          - os: windows-latest
            platform: win-64

    env:
      CHANNEL_DIR: ../eresthina-conda-channel
      DIST_DIR: dist

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v4

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          channels: conda-forge,defaults
          channel-priority: strict
          miniconda-version: latest
          activate-environment: build
          python-version: "3.10"

      - name: Install conda-build
        run: conda install --yes conda-build

      - name: Build Package
        run: conda build conda.recipe --output-folder $DIST_DIR

      - name: Clone Conda Channel Repository
        run: git clone "https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ secrets.GH_USERNAME }}/eresthina-conda-channel.git" $CHANNEL_DIR

      - name: Ensure Platform Directory Exists
        run: mkdir -p $CHANNEL_DIR/${{ matrix.platform }}

      - name: Copy Built Packages
        run: cp -r $DIST_DIR/${{ matrix.platform }}/* $CHANNEL_DIR/${{ matrix.platform }}/

      - name: Configure Git Identity
        run: |
          cd $CHANNEL_DIR
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Index and Push to Channel
        run: |
          cd $CHANNEL_DIR
          conda index .
          git add .
          git commit -m "Add ${{ matrix.platform }} packages" || echo "Nothing to commit."
          git push "https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ secrets.GH_USERNAME }}/eresthina-conda-channel.git"
